### ISSUE TITLE
Production environment hydrator error

### ISSUE THREAD

**Issue by priestor** [doctrine/DoctrineMongoDBBundle#187]
Heyhey :),

I have a problem with the cache/enviroment, I'dont know exactly. The Situation:

I'm building an API with OAuth 2.0. It runs like charm, but! Then I was stresstesting it with ab.

ab -c 10 -n 1000 http://mysite.com/api/res

Whats strange is the following output (part):

[...]
Complete requests: 121
Failed requests: 120
[...]

Its always about this +/- 10.

But why?
In another terminal I was watching the apache error.log with tail -f.
The following error code comes with the firs ab test:

PHP Fatal error: Class 'Hydrators\RessourceBundleDocumentRessourceHydrator' not found in /var/www/Ressources/Symfony/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php on line 146

and then comes, now and then, this little fella along:
(32)Broken pipe: core_output_filter: writing data to the network.

The thing is "RessourceBundleDocumentRessourceHydrator" is in the cache folder. Is this a bug? I posted it here because I think this is a problem with in the core? I was also thinking about file r/w issues.

Any help would be great! Thank you :)

**Comment by duraki** [comment]
@daniphp a little bit late with response but for anyone else, hard remove the cache (with `rm -rf`) and regenerate new hydrator classes through command `doctrine:mongodb:generate:hydrators`.

**Comment by mesanthu** [comment]
We faced a similar issue, But our case is different Just mentioning here thinking it would help someone who has a project like ours, We had multiple kernels setup for the same project what we had done is had to clear our cache with Prod env individually for each kernel, We were removing the cache folder directly as an attempt to fix the issue, But turned out that removing the folder directly will cause some other issues. so clear cache with prod mode and see if that works.
