### ISSUE TITLE
Publish XSD file on symfony.com

### ISSUE THREAD

**Issue by jmikola** [doctrine/DoctrineMongoDBBundle#221]
http://symfony.com/schema/dic/doctrine/odm/mongodb/mongodb-1.0.xsd is currently a 404.

This is necessary to ensure that configuration files are validated during tests. In the meantime, I was adding a relative `file:///` URL to `full.xsd` and testing it with the following in XmlMongoDBExtensionTest:

```
public function testLoadFullConfiguration()
{
    $container = $this->getContainer();
    $loader = new DoctrineMongoDBExtension();
    $container->registerExtension($loader);

    $this->loadFromFile($container, 'full');
}
```

**Comment by alcaeus** [comment]
Ping @javiereguiluz - is there a way we can add these files to symfony.com or should we host them on our own website?

**Comment by stof** [comment]
well, I don't even think the symfony.com website hosts the XSD files for core Symfony components. So I would suggest you to host it on your own if needed.

**Comment by alcaeus** [comment]
Agreed.

**Comment by stof** [comment]
another option is also not to host it at all, and let IDE reference it locally (which also ensure they get the version corresponding to their version of the bundle, rather than having to provide versioned URLs and hoping they keep their usage in sync with their composer.lock)

**Comment by javiereguiluz** [comment]
@stof we do host XSD for core components. E.g. -> http://symfony.com/schema/dic/services/services-1.0.xsd

But we don't do that for bundles, sorry. (and I'm sorry for not having replied to this issue on time).

**Comment by alcaeus** [comment]
No worries @javiereguiluz! I'll most likely update documentation to suggest loading the file from vendors, as that's where the current version is going to be. Otherwise we'd have to start hosting multiple versions of the file on our website which I don't think is feasible. Since we start validating XML mapping files against the schema from vendors it's best if people use that in their XML files.

**Comment by malarzm** [comment]
> Otherwise we'd have to start hosting multiple versions of the file on our website which I don't think is feasible.

This is something we need to revisit in the [docs](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/xml-mapping.html) then. It was possible to use link such as http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping-1.2.0.xsd which was redirecting to raw version of file on github but I see the redirect is now broken since we changed servers.

**Comment by alcaeus** [comment]
Hmm, maybe @jwage has an idea how to handle this. IIRC we'd have to use relative paths if we want to link to vendor, which is not good in documentation as the mapping files don't have to be in a specific directory.
