### ISSUE TITLE
Add support for Symfony 4 Bundle-less applications

### ISSUE THREAD

**Issue by altaraven** [doctrine/DoctrineMongoDBBundle#479]
As we know, Symfony 4 now follows bundle-less philosophy. But console commands like 
`doctrine:mongodb:generate:documents`
require a **bundle** argument. 
Please fix this.

**Comment by alcaeus** [comment]
We've previously mentioned it in other tickets, but we will no longer provide document generation features in this bundle or ODM directly. For ORM, the MakerBundle contains a `make:entity` command that is more flexible than the code generation tools ORM had before. I believe that ODM should go the same route, with document generation being part of MakerBundle or a library building on top of it. However, we are not willing to handle the complexity for now, especially with other, much better tools being available.

Since DocumentGenerator has been dropped from ODM 2.0, the respective commands will be dropped from the bundle before Beta 1 without replacement.

**Comment by altaraven** [comment]
Thanks for info. I hope these commands will be removed from 4.x documentation.

**Comment by alcaeus** [comment]
They will be.

**Comment by christiankasse** [comment]
which command will I use to generate documents for my database because `** #php bin/console doctrine:generate:mongodb:document**`

**Comment by christiankasse** [comment]
what will I do then in this case?
