### ISSUE TITLE
generation of documents with doctrine: mongodb: generate: documents

### ISSUE THREAD

**Issue by christiankasse** [doctrine/DoctrineMongoDBBundle#499]
which command will I use to generate documents for my database because `** #php bin/console doctrine:generate:mongodb:document**` don't work###

**Comment by jmikola** [comment]
See: https://github.com/doctrine/DoctrineMongoDBBundle/issues/498#issuecomment-434442953

This appears to be a duplicate of #498, which was already closed. In the future, it'd be preferable to follow up in the existing thread (especially if it's continuing the existing conversation) rather than create a new one.
