### ISSUE TITLE
[3.*] Is there a way to log only failed queries ?

### ISSUE THREAD

**Issue by chandon** [doctrine/DoctrineMongoDBBundle#527]
Is there a way to log only failed queries on runtime with 3.* banches ? (like when MongoCursorTimeoutException is raised, or for any other reason ?)

**Comment by alcaeus** [comment]
The exceptions produced by these failures are logged, but logging only those queries is not supported. Since the queries are logged before running the query itself, this isn't possible in 3.x.

With 4.0, there is a different, command-based logging system in place, which would also allow you to only log failed commands instead of all of them.
